name: Setup Yarn
runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
        cache: 'yarn'
        cache-dependency-path: yarn.lock
        registry-url: https://registry.npmjs.org/

    - name: Install Dependencies
      run: yarn install --frozen-lockfile
