name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CI: true

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: yarn run build

  commitlint:
    name: Commitlint
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: echo "${{ github.event.pull_request.title }}" | yarn commitlint

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: yarn run prettier

  eslint:
    name: Eslint
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: yarn run eslint --max-warnings=0

  stylelint:
    name: Stylelint
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: yarn run stylelint --max-warnings=0
