name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CI: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node & Yarn
        uses: ./.github/actions/setup-yarn

      - name: Print Environment Info
        run: yarn nx report

      - name: Build
        run: yarn run build

      - name: Commitlint
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "${{ github.event.pull_request.title }}" | yarn commitlint

      - name: Prettier
        run: yarn run prettier

      - name: Eslint
        run: yarn run eslint --max-warnings=0

      - name: Stylelint
        run: yarn run stylelint --max-warnings=0
