name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CI: true

jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'yarn'

      - run: yarn install --frozen-lockfile

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - run: yarn run build

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - run: |
          yarn run prettier
          yarn run stylelint --max-warnings=0
          yarn run eslint --max-warnings=0
