name: Firebase Deploy Next on PR

on:
  pull_request_target:
    branches:
      - main

permissions:
  checks: write
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy_next_on_pr:
    if: ${{ github.repository_owner == 'koobiq' && github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0

      - name: Setup Node & Yarn
        uses: ./.github/actions/setup-node

      - name: Build
        run: yarn run build

      - name: Deploy Documentation
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KOOBIQ }}
          firebaseToolsVersion: ^13.0.0
          expires: 5d
          channelId: data-grid-pr-${{ github.event.number }}
          projectId: koobiq
          target: next
