name: Deploy next

on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually
  workflow_dispatch:

jobs:
  deploy_next:
    if: ${{ github.repository_owner == 'koobiq' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-node
      - run: yarn run build
      - run: yarn firebase deploy --only hosting:next --token=${{ secrets.FIREBASE_DEPLOY_TOKEN }}
