name: Firebase Deploy Next

on:
  push:
    branches:
      - 'main'
  # Allows you to run this workflow manually
  workflow_dispatch:

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    if: ${{ github.repository_owner == 'koobiq' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node & Yarn
        uses: ./.github/actions/setup-node

      - name: Build
        run: yarn run build

      - name: Deploy
        run: yarn firebase deploy --only hosting:next --token=${{ secrets.FIREBASE_DEPLOY_TOKEN }}
