name: Deploy next

on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually
  workflow_dispatch:

permissions:
  contents: read # for actions/checkout to read the repository

jobs:
  deploy_next:
    if: ${{ github.repository_owner == 'koobiq' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-node
      - run: yarn run build
      - uses: FirebaseExtended/action-hosting-deploy@500ac625ca2dd40cbd15f7659af953801858032a # v0.11.0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KOOBIQ }}
          target: next
          channelId: live # reserved channel ID for the live/production site (not a temporary preview channel)
