name: E2E approve snapshots

on:
  issue_comment:
    types: [created]

jobs:
  approve_snapshots:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/approve-snapshots') }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Get branch of PR
        uses: xt0rted/pull-request-comment-branch@v2
        id: comment-branch

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}

      - name: Started comment
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: 🔄 [Updating](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) snapshots.

      - name: Setup Node & Yarn
        uses: ./.github/actions/setup-node

      - name: Setup test environment
        run: yarn run e2e:setup

      - name: Update snapshots
        run: |
          yarn run e2e:dev-ag-grid-angular --update-snapshots

      - name: Commit and push
        id: commit-and-push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'test: update e2e snapshots'
          file_pattern: '**/*.png'

      - name: Successful comment
        if: steps.commit-and-push.outputs.changes_detected == 'true'
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: ✅ Snapshots [updated](https://github.com/${{ github.repository }}/pull/${{ github.event.issue.number }}/commits/${{ steps.commit-and-push.outputs.commit_hash }})!

      - name: No changes comment
        if: steps.commit-and-push.outputs.changes_detected == 'false'
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: ⚠️ No snapshots changes detected.
