name: E2E approve snapshots

on:
  issue_comment:
    types: [created]

jobs:
  approve_snapshots:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Get branch of PR
        uses: xt0rted/pull-request-comment-branch@v2
        id: comment-branch

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}

      - name: Comment action started
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: Updating snapshots — check the [status here](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).

      - name: Setup Node & Yarn
        uses: ./.github/actions/setup-node

      - name: Setup test environment
        run: yarn run e2e:setup

      - name: Update snapshots
        run: yarn run e2e:dev-ag-grid-angular --update-snapshots

      - name: Commit and push screenshots
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'test: update e2e snapshots'
          file_pattern: '**/*.png'

      - name: Comment action successful
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: ✅ Snapshots updated!
