# Triggered workflow by PR comment: /approve-snapshots
name: E2E approve snapshots

on:
  issue_comment:
    types: [created]

permissions:
  contents: write # for stefanzweifel/git-auto-commit-action to push changes
  pull-requests: write # for thollander/actions-comment-pull-request to comment on PRs

jobs:
  approve_snapshots:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/approve-snapshots') }}
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 10
    steps:
      - uses: xt0rted/pull-request-comment-branch@v3
        id: comment-branch
      - uses: actions/github-script@v7
        with:
          script: |
            await github.rest.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              content: 'eyes',
            });
      - uses: actions/checkout@v7
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}
      - run: npm run e2e:docker:update-snapshots
      - uses: stefanzweifel/git-auto-commit-action@v7
        id: commit-and-push
        with:
          commit_message: 'test: updated e2e snapshots'
          file_pattern: '**/*.png **/*.txt'
      - uses: actions/github-script@v7
        if: ${{ steps.commit-and-push.outputs.changes_detected == 'true' }}
        with:
          script: |
            await github.rest.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              content: 'rocket',
            });
      - uses: thollander/actions-comment-pull-request@v3
        if: ${{ steps.commit-and-push.outputs.changes_detected != 'true' }}
        with:
          message: ⚠️ No snapshots changes detected.
      - uses: thollander/actions-comment-pull-request@v3
        if: ${{ failure() }}
        with:
          message: 🚨 Failed to [update](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) snapshots.
