name: E2E tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node & Yarn
        uses: ./.github/actions/setup-node

      - name: Setup test environment
        run: yarn run e2e:setup

      - name: Run e2e tests
        id: run-e2e-tests
        run: |
          yarn run e2e:dev-ag-grid-angular

      - name: Upload report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        id: upload-report
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 5

      - name: Failure comment
        if: ${{ failure() && steps.run-e2e-tests.outcome == 'failure' }}
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            ### 🚨 E2E tests failed

            Review the [report](${{ steps.upload-report.outputs.artifact-url }}) for details.

            ---

            💡 Comment `/approve-snapshots` to approve snapshot changes.
