name: E2E tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node & Yarn
        uses: ./.github/actions/setup-node

      - name: Setup test environment
        run: yarn run e2e:setup

      - name: Run e2e tests
        run: |
          yarn run e2e:dev-ag-grid-angular | tee output.log
          if grep -q -e "Error: A snapshot doesn't exist at" -e "Screenshot comparison failed" output.log; then
            echo "E2E tests failed: Visual snapshot differences detected"
            echo "SNAPSHOT_DIFFERENCES_DETECTED=true" >> $GITHUB_ENV
            exit 1
          elif grep -q "failed" output.log; then
            echo "E2E tests failed: Non-snapshot related errors detected"
            exit 1
          fi

      - name: Upload report
        uses: actions/upload-artifact@v4
        id: upload-report
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 1

      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v3
        if: failure() && env.SNAPSHOT_DIFFERENCES_DETECTED == 'true'
        with:
          message: |
            ### 📸 Snapshot differences detected
            Review the [report](${{ steps.upload-report.outputs.artifact-url }}) for details.
            Comment `/approve-snapshots` to approve changes.
