name: PR deploy next

on:
  pull_request_target:
    branches:
      - main

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  deploy:
    if: ${{ github.repository_owner == 'koobiq' && github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0
      - uses: ./.github/actions/setup-node
      - run: yarn run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KOOBIQ }}
          firebaseToolsVersion: ^13.35.1
          expires: 5d
          target: next
          channelId: data-grid-pr-${{ github.event.number }}
