name: Publish

on:
  release:
    types:
      - created
  # Allows you to run this workflow manually
  workflow_dispatch:

permissions:
  contents: read
  # Needed for provenance data generation
  # https://nx.dev/recipes/nx-release/publish-in-ci-cd#npm-provenance
  id-token: write

jobs:
  publish:
    if: ${{ github.repository_owner == 'koobiq' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-node
      - run: yarn nx release publish --registry=https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
