name: Publish

on:
  release:
    types:
      - created
  # Allows you to run this workflow manually
  workflow_dispatch:

permissions:
  contents: read
  # Needed for provenance data generation
  # https://nx.dev/recipes/nx-release/publish-in-ci-cd#npm-provenance
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    if: ${{ github.repository_owner == 'koobiq' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node & Yarn
        uses: ./.github/actions/setup-node

      - name: Publish
        run: yarn nx release publish --registry=https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
